# ---------------------------------------------------------------------------
# Installer
# ---------------------------------------------------------------------------
# Written by hand rather than generated by CPack, for two reasons that both show
# up immediately when it is used here: the Start Menu shortcut is generated from
# the CMake target name, so it points at "VYNX_QR.exe" rather than at
# "VYNX QR.exe", and CPack's generator still asks for an administrator, which is
# wrong for a per-user utility. This script is per-user, names the executable
# correctly, and registers an Apps and Features entry.

if(VYNX_BUILD_APP)
set(VYNX_PAYLOAD_DIR "${CMAKE_BINARY_DIR}/bin")
set(VYNX_PACKAGE_DIR "${CMAKE_BINARY_DIR}/package")
file(MAKE_DIRECTORY "${VYNX_PACKAGE_DIR}")
find_package(Python3 REQUIRED COMPONENTS Interpreter)
add_custom_target(license_payload
  COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/scripts/generate-rust-licenses.py"
          --output "${VYNX_PAYLOAD_DIR}/licenses/rust"
          --cache "${CMAKE_BINARY_DIR}/license-tools"
  COMMAND "${CMAKE_COMMAND}" "-DSOURCE=${CMAKE_SOURCE_DIR}"
          "-DPAYLOAD=${VYNX_PAYLOAD_DIR}" "-DQT_VERSION=${Qt6_VERSION}"
          -P "${CMAKE_SOURCE_DIR}/cmake/package-licenses.cmake"
  VERBATIM)

# Point NSIS at the same payload directory the build produced.
configure_file("${CMAKE_SOURCE_DIR}/installer/vynx_qr.nsi" "${VYNX_PACKAGE_DIR}/vynx_qr.nsi" @ONLY)

find_program(MAKENSIS_EXECUTABLE makensis
  HINTS "$ENV{LOCALAPPDATA}/tauri/NSIS" "C:/Program Files (x86)/NSIS"
)
if(NOT MAKENSIS_EXECUTABLE)
  # Not fatal: the application and its tests build without an installer.
  message(STATUS "makensis was not found, so the installer target is unavailable")
else()
  add_custom_target(installer
    COMMAND "${MAKENSIS_EXECUTABLE}" "/DVYNX_VERSION=${PROJECT_VERSION}"
            "/DVYNX_PAYLOAD_DIR=${VYNX_PAYLOAD_DIR}"
            "/DVYNX_ICON=${VYNX_RC_ICON}"
            "/DVYNX_LICENSE=${CMAKE_SOURCE_DIR}/LICENSE"
            "/XSetCompressor /SOLID lzma"
            "/XOutFile ${VYNX_PACKAGE_DIR}/VYNX-QR-Setup-x64-${PROJECT_VERSION}.exe"
            "${VYNX_PACKAGE_DIR}/vynx_qr.nsi"
    DEPENDS VYNX_QR license_payload "${VYNX_PACKAGE_DIR}/vynx_qr.nsi"
    COMMENT "Building the NSIS installer"
    VERBATIM
  )
endif()

# ---------------------------------------------------------------------------
# Portable archive
# ---------------------------------------------------------------------------
# The same payload with nothing installed: useful to run from a USB stick, and it
# costs one archive step rather than a second packaging tool.
  add_custom_target(portable
    COMMAND "${CMAKE_COMMAND}" -E tar czf
            "${VYNX_PACKAGE_DIR}/VYNX-QR-Portable-x64-${PROJECT_VERSION}.zip"
            --format=zip "VYNX QR.exe" "Qt6Core.dll" "Qt6Gui.dll" "Qt6Widgets.dll"
            "platforms" "styles" "licenses" "LICENSE" "THIRD_PARTY_LICENSES.md"
    WORKING_DIRECTORY "${VYNX_PAYLOAD_DIR}"
    DEPENDS VYNX_QR license_payload
    COMMENT "Building the portable archive"
    VERBATIM
  )
endif()

